blank_issues_enabled: true
contact_links:
  - name: React Text Igniter
    url: https://mindfiredigital.github.io/react-text-igniter/
    about: react-text-igniter is a tool that allows developers to integrate HTML Editor using React.
